services:
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - WARP_SLEEP=5
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./warpdata:/var/lib/cloudflare-warp
    networks:
      - internal_network  # 浣跨敤鍐呴儴缃戠粶锛屼笉瀵瑰鏆撮湶绔彛
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "https://www.google.com"]  # 闈欓粯妯″紡涓嬭姹侴oogle锛屽鏋滄垚鍔熻繑鍥?xx鐘舵€佺爜
      interval: 30s  # 姣忛殧30绉掓鏌ヤ竴娆?
      timeout: 10s   # 璇锋眰瓒呮椂10绉?
      retries: 3     # 澶辫触3娆″悗鏍囪涓轰笉鍋ュ悍
      start_period: 5s  # 瀹瑰櫒鍚姩鍚庣瓑寰?绉掑啀寮€濮嬫鏌?
      
  chat2api:
    image: lanqian528/chat2api:latest
    container_name: chat2api
    restart: unless-stopped
    ports:
      - '5005:5005'  # 鏆撮湶chat2api鏈嶅姟渚涘閮ㄨ闂?
    environment:
      - TZ=Asia/Shanghai
      - AUTHORIZATION=sk-xxx
      - ADMIN_API_KEY=change-me
      - PROXY_URL=socks5://warp:1080  # 璁剧疆 PROXY_URL 涓?warp 瀹瑰櫒鐨勪唬鐞嗗湴鍧€
    depends_on:
      warp:
        condition: service_healthy  # 鍙湁 warp 鐨勫仴搴锋鏌ラ€氳繃鏃讹紝chat2api 鎵嶄細鍚姩
    networks:
      - internal_network  # chat2api 鍜?warp 鍦ㄥ悓涓€涓唴閮ㄧ綉缁?
    volumes:
      - ./data:/app/data # 鎸傝浇涓€浜涢渶瑕佷繚瀛樼殑鏁版嵁

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 300 chat2api
    
networks:
  internal_network:
    driver: bridge  # 瀹氫箟涓€涓ˉ鎺ョ綉缁?

